-- banco de preguntas en SQL (38 reactivos actuales, amplíe según sea necesario)
CREATE TABLE exam_questions( id INTEGER PRIMARY KEY AUTOINCREMENT, section TEXT, question TEXT, answer TEXT);
CREATE TABLE choices( qid INTEGER, opt TEXT, val TEXT);

INSERT INTO exam_questions(id,section,question,answer) VALUES
(1,'CNPP','El proceso penal en México es:','B'),
(2,'CNPP','Son principios rectores del proceso penal, excepto:','C'),
(3,'CNPP','El principio de publicidad implica que:','C'),
(4,'CNPP','El principio de contradicción permite:','B'),
(5,'CNPP','El principio de continuidad significa que las audiencias serán:','C'),
(6,'CNPP','El principio de inmediación exige:','B'),
(7,'CNPP','La presunción de inocencia se mantiene hasta:','C'),
(8,'CNPP','El doble enjuiciamiento está:','B'),
(9,'CNPP','La prisión preventiva es de carácter:','B'),
(10,'CNPP','El derecho a la defensa debe ejercerse con:','C'),
(11,'LGV','Son víctimas directas:','B'),
(12,'LGV','Las víctimas indirectas son:','B'),
(13,'LGV','El principio de dignidad implica:','B'),
(14,'LGV','El principio de buena fe obliga a:','B'),
(15,'LGV','La reparación debe ser:','C'),
(16,'Inteligencia','La inteligencia criminal se enfoca en:','B'),
(17,'Inteligencia','El nivel estratégico de inteligencia busca:','B'),
(18,'Inteligencia','El nivel táctico se orienta a:','C'),
(19,'Inteligencia','El ciclo de inteligencia inicia con:','B'),
(20,'Inteligencia','La etapa final del ciclo es:','C'),
(21,'PrimerRespondiente','El Primer Respondiente debe privilegiar:','C'),
(22,'PrimerRespondiente','Los supuestos de actuación del Primer Respondiente son:','A'),
(23,'PrimerRespondiente','Si el MP no recibe la puesta a disposición, el policía debe:','B'),
(24,'CadenaCustodia','La Cadena de Custodia garantiza:','C'),
(25,'CadenaCustodia','La Cadena de Custodia inicia con:','C'),
(26,'CadenaCustodia','La apertura del embalaje debe:','B'),
(27,'ProteccionDatos','Las medidas de seguridad deben ser:','B'),
(28,'ProteccionDatos','El análisis de riesgo considera:','B'),
(29,'ProteccionDatos','Los derechos ARCO significan:','B'),
(30,'Transparencia','La información en posesión de sujetos obligados es:','C'),
(31,'Transparencia','El acceso a la información es:','B'),
(32,'Transparencia','El solicitante debe justificar interés:','C'),
(33,'Analisis','El análisis táctico identifica:','B'),
(34,'Analisis','El análisis estratégico examina:','A'),
(35,'Analisis','El análisis investigativo busca:','B'),
(36,'Analisis','El análisis administrativo se usa para:','B'),
(37,'Analisis','El análisis operacional evalúa:','B'),
(38,'Analisis','La inteligencia criminal moderna reemplaza doctrinas basadas en:','B');

INSERT INTO choices(qid,opt,val) VALUES
(1,'A','Inquisitivo y escrito'),
(1,'B','Acusatorio y oral'),
(1,'C','Mixto y reservado'),
(1,'D','Administrativo y documental'),
(2,'A','Publicidad'),
(2,'B','Contradicción'),
(2,'C','Secrecía absoluta'),
(2,'D','Inmediación'),
(3,'A','Solo las partes pueden asistir'),
(3,'B','Las audiencias son privadas'),
(3,'C','El público puede acceder salvo excepciones'),
(3,'D','Solo el juez puede presenciar'),
(4,'A','Oponerse a resoluciones firmes'),
(4,'B','Conocer y controvertir pruebas'),
(4,'C','Suspender audiencias'),
(4,'D','Delegar funciones'),
(5,'A','Esporádicas'),
(5,'B','Secretas'),
(5,'C','Continuas y sucesivas'),
(5,'D','Escritas'),
(6,'A','Delegación en secretarios'),
(6,'B','Presencia del órgano jurisdiccional'),
(6,'C','Uso exclusivo de medios electrónicos'),
(6,'D','Juicios escritos'),
(7,'A','Detención'),
(7,'B','Vinculación'),
(7,'C','Sentencia firme'),
(7,'D','Denuncia'),
(8,'A','Permitido'),
(8,'B','Prohibido'),
(8,'C','Limitado'),
(8,'D','Facultado al MP'),
(9,'A','Obligatorio'),
(9,'B','Excepcional'),
(9,'C','Permanente'),
(9,'D','Administrativo'),
(10,'A','Cualquier ciudadano'),
(10,'B','Policía'),
(10,'C','Defensor titulado'),
(10,'D','Ministerio Público'),
(11,'A','Testigos'),
(11,'B','Personas que sufren daño por delito'),
(11,'C','Policías'),
(11,'D','Servidores públicos'),
(12,'A','Periodistas'),
(12,'B','Familiares de la víctima directa'),
(12,'C','MP'),
(12,'D','Peritos'),
(13,'A','Discrecionalidad estatal'),
(13,'B','Respeto como fin y no medio'),
(13,'C','Criminalización'),
(13,'D','Reserva procesal'),
(14,'A','Sospechar de la víctima'),
(14,'B','Presumir su veracidad'),
(14,'C','Negar ayuda'),
(14,'D','Judicializar todo'),
(15,'A','Parcial'),
(15,'B','Económica únicamente'),
(15,'C','Integral y transformadora'),
(15,'D','Discrecional'),
(16,'A','Ideología'),
(16,'B','Organizaciones delictivas'),
(16,'C','Partidos políticos'),
(16,'D','Opinión pública'),
(17,'A','Capturas inmediatas'),
(17,'B','Planeación a mediano y largo plazo'),
(17,'C','Detenciones urgentes'),
(17,'D','Flagrancia'),
(18,'A','Política pública'),
(18,'B','Prevención general'),
(18,'C','Operativos específicos'),
(18,'D','Reformas legislativas'),
(19,'A','Difusión'),
(19,'B','Recolección'),
(19,'C','Planeación'),
(19,'D','Retroalimentación'),
(20,'A','Procesamiento'),
(20,'B','Planeación'),
(20,'C','Retroalimentación'),
(20,'D','Análisis'),
(21,'A','Evidencia'),
(21,'B','Detención'),
(21,'C','Vida humana'),
(21,'D','Persecución'),
(22,'A','Denuncia, flagrancia y descubrimiento'),
(22,'B','Solo flagrancia'),
(22,'C','Solo denuncia'),
(22,'D','Judicialización'),
(23,'A','Retirarse'),
(23,'B','Informar a su superior y elaborar constancia'),
(23,'C','Liberar detenido'),
(23,'D','Destruir evidencia'),
(24,'A','Publicidad'),
(24,'B','Legalidad administrativa'),
(24,'C','Mismidad y autenticidad'),
(24,'D','Transparencia presupuestal'),
(25,'A','Juicio'),
(25,'B','Sentencia'),
(25,'C','Preservación del lugar'),
(25,'D','Peritaje final'),
(26,'A','Romper sello original'),
(26,'B','Abrirse por lado distinto al sellado'),
(26,'C','No documentarse'),
(26,'D','Hacerse sin registro'),
(27,'A','Solo técnicas'),
(27,'B','Administrativas, físicas y técnicas'),
(27,'C','Opcionales'),
(27,'D','Verbales'),
(28,'A','Solo tecnología'),
(28,'B','Amenazas y vulnerabilidades'),
(28,'C','Presupuesto'),
(28,'D','Publicidad'),
(29,'A','Archivo, Registro, Consulta, Opinión'),
(29,'B','Acceso, Rectificación, Cancelación, Oposición'),
(29,'C','Autenticidad, Registro, Control, Observación'),
(29,'D','Análisis, Regulación, Control, Organización'),
(30,'A','Privada'),
(30,'B','Reservada'),
(30,'C','Pública salvo excepciones'),
(30,'D','Confidencial siempre'),
(31,'A','Condicionado'),
(31,'B','Gratuito'),
(31,'C','Solo judicial'),
(31,'D','Discrecional'),
(32,'A','Sí'),
(32,'B','Solo judicialmente'),
(32,'C','No'),
(32,'D','Solo con abogado'),
(33,'A','Tendencias a largo plazo'),
(33,'B','Patrones para intervención inmediata'),
(33,'C','Reformas legislativas'),
(33,'D','Política criminal'),
(34,'A','Escenarios y tendencias'),
(34,'B','Detenciones individuales'),
(34,'C','Flagrancia'),
(34,'D','Audiencias'),
(35,'A','Presupuesto'),
(35,'B','Vincular casos y modus operandi'),
(35,'C','Transparencia'),
(35,'D','Control administrativo'),
(36,'A','Perfil criminal'),
(36,'B','Mapas e indicadores'),
(36,'C','Interrogatorio'),
(36,'D','Sentencias'),
(37,'A','Política pública'),
(37,'B','Despliegue de recursos'),
(37,'C','Delitos federales'),
(37,'D','Tratados internacionales'),
(38,'A','Prevención'),
(38,'B','Guerra ideológica'),
(38,'C','Democracia'),
(38,'D','Seguridad pública');